WebApplication/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^video/', include('video.urls')),
    # url(r'^', include('video.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

media/TimePass/TimePass/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^video/', include('video.urls')),
]

media/TimePass/video/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
]

video/urls.py
from django.conf.urls import url
# from django.conf.urls import patterns
from . import views


app_name = 'video'

urlpatterns = [
    # patterns('video.views'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<video_id>[0-9]+)/$', views.details, name='details'),
    url(r'^(?P<video_id>[0-9]+)/video/add/$', views.VideoCreate.as_view(), name='video-add'),
    url(r'^video/(?P<pk>[0-9]+)/$', views.VideoUpdate.as_view(), name='video-update'),
    url(r'^video/(?P<pk>[0-9]+)/delete/$', views.VideoDelete.as_view(),  name='video-delete'),
    url(r'^registration/$', views.UserFormView.as_view(), name='registration'),
    url(r'^login/$', views.UserLoginView.as_view(), name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    # /video/profile/<user_id>
    url(r'^user/(?P<user_id>[0-9]+)/$',  views.UserProfileView,  name='user_profile'),
    # /video/search
    url(r'^discover/$', views.discover, name='discover'),
    url(r'^comment/(?P<video_id>[0-9]+)/$', views.CommentView, name='comment'),
]

media/TimePass/video/models.py
from __future__ import unicode_literals

from django.db import models


class User(models.Model):
    user_name = models.CharField(max_length=250)
    email = models.CharField(max_length=300)
    password = models.CharField(max_length=300)

    def __str__(self):
        return self.user_name


class Video(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    Description = models.CharField(max_length=1000)
    thumbnail = models.CharField(max_length=2000)
    video = models.CharField(max_length=2000)

    def __str__(self):
        return self.title

video/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
# from myapplication.essay.models import Essay
# from django.contrib import admin

# Create your models here.


class Video(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=500)
    description = models.CharField(max_length=1000)
    thumbnail = models.FileField(max_length=1000)
    video_path = models.FileField(max_length=1000)
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('video:details', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class UserFeedback(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    comment = models.CharField(max_length=1000)
    like = models.PositiveSmallIntegerField(default=0)
    dislike = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return "Comment:-" + self.comment

video/forms.py
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout, get_user_model
from django import forms
from .models import Video, UserFeedback


User = get_user_model()


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class UserLogin(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        user = authenticate(username=username, password=password)

        if not user:
            raise forms.ValidationError("This user does not exist")
        if not user.check_password(password):
            raise forms.ValidationError("Incorrect Password")
        if not user.is_active:
            raise forms.ValidationError("This user is not longer active")
        return super(UserLogin, self).clean(*args, **kwargs)


class AddVideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['title', 'description', 'thumbnail', 'video_path']


class UserFeedbackForm(forms.ModelForm):
    class Meta:
        model = UserFeedback
        fields = ['comment']

media/TimePass/video/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render
from .models import User, Video


def home(request):
    all_video = User.objects.all()
    return render(request,'video/home_page.html', {'all_video': all_video})

video/views.py
from django.views import generic
from django.views.generic.edit import CreateView,  DeleteView,  UpdateView
from django.urls import reverse_lazy
from .models import Video, UserFeedback
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View, FormView
from .forms import UserForm, UserLogin, AddVideoForm, UserFeedbackForm
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.urls import reverse
# from myapplication.essay.models import Essay
# from django.contrib import admin


class IndexView(generic.ListView):
    model = User
    template_name = 'video/index.html'

    def get_queryset(self):
        return Video.objects.all()


def details(request, video_id):
    all_video = Video.objects.all()
    # object_list = Video.objects.filter(userfeedback__video=video_id)
    object_list = Video.objects.get(pk=video_id)
    video = get_object_or_404(Video, pk=video_id)
    return render(request, 'video/details.html', {
        'video': video,
        'all_video': all_video,
        'object_list': object_list,
    })


class DetailView(generic.DetailView):
    # model = Video
    model = User
    template_name = 'video/details.html'

    def get_queryset(self):

        return Video.objects.get()


def UserProfileView(request, user_id):
    template_name = 'video/profile.html'
    user = get_object_or_404(User, pk=user_id)
    return render(request, template_name, {'user': user})


class VideoCreate(CreateView):
    # template_name = 'video/video_form.html'
    form_class = AddVideoForm

    def get(self, request, video_id):
        if not request.user.is_authenticated():
            return render(request, 'video/login_form.html')
        else:
            user = get_object_or_404(User, pk=video_id)
            form = self.form_class(None, None)
            return render(request,  'video/video_form.html', {'form': form})

    def post(self, request, video_id):
        if not request.user.is_authenticated():
            return render(request, 'video/login_form.html')
        else:
            user = get_object_or_404(User, pk=video_id)
            form = self.form_class(request.POST, request.FILES)

            if form.is_valid():
                video = form.save(commit=False)
                video.user = user
                video.thumbnail = request.FILES['thumbnail']
                video.video_path = request.FILES['video_path']
                video.save()
                return render(request, 'video/profile.html', {'form': form})

            return render(request,  'video/video_form.html', {'form': form})


class VideoUpdate(UpdateView):
    model = Video
    fields = ['title', 'description', 'thumbnail', 'video_path']


class VideoDelete(DeleteView):
    model = Video
    success_url = reverse_lazy('video:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'video/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('video:index')

        return render(request, self.template_name, {'form': form})


class UserLoginView(FormView):
    template_name = 'video/login_form.html'
    form_class = UserLogin

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('video:index')

        return render(request, self.template_name, {'form': form})


def logout_view(request):
    logout(request)
    return redirect('video:login')


def discover(request):
    query = request.GET.get("q")
    if query:
        object_list = Video.objects.filter(title__icontains=query)
        return render(request, 'video/discover.html', {'object_list': object_list})
    else:
        object_list = Video.objects.all()
        return render(request, 'video/index.html', {'object_list': object_list})


# class CommentView(CreateView):
#     template_name = 'video/details.html'
#     form_class = UserFeedback
#
#     def get(self, request, pk):
#         if not request.user.is_authenticated():
#             return render(request, 'video/login_form.html')
#         else:
#             video = Video.objects.get(pk=pk)
#             form = self.form_class(None, None)
#             return render(request,  'video/details.html', {'form': form})
#
#     def post(self, request, pk):
#         com = request.GET.get("comment")
#         if not request.user.is_authenticated():
#             return render(request, 'video/login_form.html')
#         else:
#             video = Video.objects.get(pk=pk)
#             form = self.form_class(request.POST)
#             if form.is_valid():
#                 comment = form.save(commit=False)
#                 comment.video = video
#                 comment.comment = com
#                 comment.save()
#                 user_comment = UserFeedback.objects.all()
#                 return render(request, 'video/details.html', {
#                     'form': form,
#                     'user_comment': user_comment, })
#             return render(request,  'video/details.html', {'form': form})


def CommentView(request, video_id):
    if request.method == 'POST':
        form = UserFeedbackForm(request.POST)
        if form.is_valid():
            comment = request.POST.get('comment')
            video = Video.objects.get(pk=video_id)
            feedback = UserFeedback(video=video, comment=comment)
            feedback.save()
            # return redirect('video:comment')
            # return render(request, 'video/details.html', {'form': form})
            return redirect('video:details', video_id)
            # return redirect("{% url 'video:details' video_id %}")

        else:
            form = UserFeedbackForm()
        return render(request, 'video/details.html', {'form': form})

video/templates/video/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Time Pass</title>
    {% load staticfiles %}
    <link rel="icon" href="{% static 'video/image/TimeP.png' %}">
<link rel="stylesheet" href="{% static 'video/style.css' %}">

        <link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/uniwide"
              type="text/css"/>

<link rel="stylesheet" href="{% static 'video/css/bootstrap-theme.min.css' %}">

<link rel="stylesheet" href="{% static 'video/css/bootstrap.min.css' %}">

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
      integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
      crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
            data-targer="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{% url 'video:index' %}" class="navbar-brand"
               style="font-size: 2em;"><img src="{% static 'video/image/TimePass.png' %}" alt=""></a>
        </div>

        <!--Item-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'video:index' %}">
                        <span class=" glyphicon glyphicon-facetime-video" aria-hidden="true"></span> &nbsp;
                        Video</a>
                </li>

                <li class="#">
                    {%if user.username%}
                    <a href="{% url 'video:user_profile' user.id %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span> &nbsp;
                        {{user.username}}</a>
                        {%endif%}
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="{%url 'video:discover' %}">
                <div class="form-group">
                    <input type="text" class="form-control glyphicon glyphicon-search " name="q" value="" placeholder = " ">
                </div>
                <button type="submit" class="btn btn-default" >Discover</button>
            </form>

            <ul class="nav navbar-nav navbar-right ">

                <li class="#">
                    {%if user.username%}
                    <a href="{% url 'video:video-add' user.id %}">
                        <span class="glyphicon glyphicon-open" aria-hidden="true"></span> &nbsp;
                        Add Video</a>
                        {%else%}
                        <a href="{% url 'video:registration' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> &nbsp;
                            Sign up</a>
                        {%endif%}
                </li>

                <li class="#">
                    {%if user.username%}
                    <a href={% url 'video:logout' %}>
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span> &nbsp;
                        Logout</a>
                    {%else%}
                    <a href={% url 'video:login' %}>
                        <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> &nbsp;
                        Signin</a>
                    {%endif%}
                </li>
            </ul>

        </div>
    </div>
</nav>

<div class="main-body ">
    {% block body %}
    {% endblock %}
</div>

<nav class="navbar navbar-default col-sm-12 col-md-12 col-lg-12">
  <div class="container">
    <p style="text-align: center;">@This web application created by Sayeed</p>
  </div>
</nav>
</body>
</html>

video/templates/video/details.html
{% extends 'video/base.html' %}
{% block body %}

<div class="container">


<div class="row">
    <div class="col-sm-4 col-md-6 col-lg-9">
            <div class="video">
                <video src="{{video.video_path.url}}"  style="max-height:540px; background-color:black"  width="100%"
                autoplay poster="posterimage.jpg" controls>
                </video>
                <h2>{{video.title}}</h2>
                <h5 class="text-muted">{{video.description}}</h5>
            </div>
    </div>

</div>

    <div class="container-fluid">
        <div class="container-fluid">
                            <form class="form-horizontal col-sm-4 col-md-6 col-lg-9" action="{% url 'video:comment' video.id %}" method="post">
                            {%csrf_token%}
                            <div class="form-group">

                                <label for="comment" class="control-label">Comment:</label>
                                <textarea id="comment" class="form-control" name="comment" style="max-width: 75%; text-align:left;">
                                </textarea>

                            </div>
                                <div class="form-group">
                                    <input type="submit" class="btn btn-success col-sm-1 col-md-1 col-lg-1" value="Submit">
                                </div>
                        </form>
        </div>
        <div class="col-sm-4 col-md-6 col-lg-9">
                     {%if object_list%}
                     {%for comment in object_list.userfeedback_set.all%}
                    <div class="form-group">
                    <p id="user">{{video.user}}</p>
                    <label  for="user"> {{comment.comment}}</label><hr>
                    </div>
                        {%endfor%}
                         {%endif%}
        </div>
    </div>
    <div>
        <!-- <p>vnbvnb</p> -->
        {% if all_video%}
        <div class="row">
            {% for video in all_video%}
            <div class="col-sm-4 col-lg-3 video_part ">
                <div class="thumbnail">
                        <a href="{% url 'video:details' video.id%}">
                        <img src="{{video.thumbnail.url}}" alt="image" class="img-responsive"></a>
                </div>
                <div class="caption">
                        <a href="{% url 'video:details' video.id%}">  <h3>{{video.title}}</h3></a>
                        <h4 class="text-muted">{{ video.user}}</h4>
                </div>

            </div>
            {%endfor%}
        </div>
            {%endif%}
    </div>

</div>
{% endblock %}

video/templates/video/discover.html
{% extends 'video/base.html' %}
{% block body %}
{% if object_list%}
<div class="container">
<div class="row">
    {% for video in object_list%}
    <div class="col-sm-4 col-lg-3 video_part ">
        <div class="thumbnail">
                <a href="{% url 'video:details' video.id%}">
                <img src="{{video.thumbnail.url}}" alt="image" class="img-responsive"></a>
        </div>
        <div class="caption">
                <a href="{% url 'video:details' video.id%}">  <h3>{{video.title}}</h3></a>
                <h4 class="text-muted">{{ video.user}}</h4>
        </div>

    </div>
    {%endfor%}
</div>
</div>
{%endif%}
{% endblock %}

video/templates/video/form-template.html
{% for field in form %}
    <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10 ">
        <span class="text-danger small">
            {{ field.errors }}
        </span>
    </div>
        <label class="control-label col-sm-2">
            {{ field.label_tag }}
        </label>
    <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

video/templates/video/index.html
{% extends 'video/base.html' %}
{% block body %}
{% if error_message %}
           <p><strong>{{ error_message }}</strong></p>
       {% endif %}

<div class="container">
<div class="row">
    {% for video in object_list%}
    <div class="col-sm-4 col-lg-3 video_part ">
        <div class="thumbnail">
                <a href="{% url 'video:details' video.id%}">
                <img src="{{video.thumbnail.url}}" alt="image" class="img-responsive"></a>
        </div>
        <div class="caption">
                <a href="{% url 'video:details' video.id%}">  <h3>{{video.title}}</h3></a>
                <h4 class="text-muted">{{ video.user}}</h4>
        </div>

    </div>
    {%endfor%}
</div>
</div>


    <!-- <div class="container">
        <table >
            {% for video in object_list %}
                <tr class="video" >
                <td>
                    <a href="{% url 'video:details' video.id %}">
                        <span>
                        <img src="{{ video.thumbnail.url }}" alt="Image" class="img-thumbnail  ">
                        <p class="text-muted">{{ video.title }}</p>
                        </span>
                    </a>
                </td>
                </tr>
            {% endfor %}
        </table>

    </div> -->

{% endblock %}

video/templates/video/login_form.html
{% extends 'video/base.html' %}

{% block body %}
    <div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-7 col-lg-8">
            <div class="panel panel-default">
                <div class="panel-body">
                        <h1 class='"form-group"'>Login!!!</h1>
                        <hr>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'video/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2  col-sm-10">
                                <button type="submit" class="btn btn-success">Login!</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

video/templates/video/profile.html
{%extends 'video/base.html'%}
{%block body%}
<div class="container">
<div class="row">
    {%if user.video_set.all%}
    {% for video in user.video_set.all%}
    <div class="col-sm-4 col-lg-3 video_part ">
        <div class="thumbnail">
                <a href="{% url 'video:details' video.id%}">
                <img src="{{video.thumbnail.url}}" alt="image" class="img-responsive"></a>
        </div>
        <div class="caption">
                <a href="{% url 'video:details' video.id%}">  <h3>{{video.title}}</h3></a>
                <h4 class="text-muted">{{ video.user}}</h4>

                <!--View Details-->
                <a href="{% url 'video:video-update' video.id %}" class="btn btn-primary btn-sm"
                role="button"><span class="glyphicon glyphicon-edit" aria-hidden="true">Edit</span></a>

                <!--Delete-->
                <form action="{% url 'video:video-delete' video.id %}" method="post" style="display:inline;">
                    {% csrf_token %}
            <input type="hidden" name="video_id" value="{{ video.id }}"/>
            <button type="submit" class="btn btn-danger btn-sm">
                <span class="glyphicon glyphicon-trash">Delete</span>
    </button>
</form>


        </div>

    </div>
    {%endfor%}
</div>
</div>

{%else%}
<h2>No Video Found...</h2>
{%endif%}

{%endblock%}

video/templates/video/registration_form.html
{% extends 'video/base.html' %}

{% block body %}
    <div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-7 col-lg-8">
            <div class="panel panel-default">
                <div class="panel-body">
                        <h1 class='"form-group"'>Registration Now!!!</h1>
                        <hr>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'video/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2  col-sm-10">
                                <button type="submit" class="btn btn-success">Sing up!</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

video/templates/video/video_form.html
{% extends 'video/base.html' %}

{% block body %}
    <div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-7 col-lg-8">
            <div class="panel panel-default">
                <div class="panel-body">
                        <h1 class='"form-group"'>Upload your video</h1>
                        <hr>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'video/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2  col-sm-10">
                                <button type="submit" class="btn btn-success">Publish</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}